
apiVersion: v1
kind: PersistentVolume
metadata:
  name: argo-workflow-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    # This path should be under the nodes.extraMounts.containerPath of kind-cluster.yaml if we want to retain data after cluster deletion
    # as this is not a path on the host machine, but a path inside the kind node container (which is our host for the k8s cluster)
    path: /mnt/argo-workflow
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-workflow-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
  storageClassName: ""
