
apiVersion: v1
kind: PersistentVolume
metadata:
  name: argo-workflow-input-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /mnt/argo-workflow-input
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-workflow-input-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""