
apiVersion: v1
kind: PersistentVolume
metadata:
  name: argo-workflow-input-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: /mnt/argo-workflow-input
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-workflow-input-pvc
  namespace: argo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: argo-workflow-output-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    # This path should be under the nodes.extraMounts.containerPath of kind-cluster.yaml if we want to retain data after cluster deletion
    # as this is not a path on the host machine, but a path inside the kind node container (which is our host for the k8s cluster)
    path: /mnt/argo-workflow-output
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: argo-workflow-output-pvc
    namespace: argo
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi
    storageClassName: ""
